# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.image_filter_parameters import ImageFilterParameters  # noqa: E501
from openapi_client.rest import ApiException

class TestImageFilterParameters(unittest.TestCase):
    """ImageFilterParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImageFilterParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.image_filter_parameters.ImageFilterParameters()  # noqa: E501
        if include_optional :
            return ImageFilterParameters(
                file_id = '0', 
                page_range = '0', 
                filters = [
                    'addNoise'
                    ], 
                roi_left = 56, 
                roi_top = 56, 
                roi_width = 56, 
                roi_height = 56, 
                gaussian_kernel_size = 56, 
                unsharp_mask_radius = 56, 
                unsharp_mask_amount = 1.337, 
                unsharp_mask_threshold = 56, 
                subtract_background_rolling_ball_size = 56, 
                subtract_background_light_background = True, 
                median_kernel_size = 56, 
                min_kernel_size = 56, 
                max_kernel_size = 56, 
                soften_value = 56, 
                colorize_hue = 1.337, 
                colorize_saturation = 1.337, 
                colorize_luminosity = 1.337
            )
        else :
            return ImageFilterParameters(
                file_id = '0',
                page_range = '0',
                filters = [
                    'addNoise'
                    ],
        )

    def testImageFilterParameters(self):
        """Test ImageFilterParameters"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
