# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.rotate_mode import RotateMode  # noqa: E501
from openapi_client.rest import ApiException

class TestRotateMode(unittest.TestCase):
    """RotateMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RotateMode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.rotate_mode.RotateMode()  # noqa: E501
        if include_optional :
            return RotateMode(
            )
        else :
            return RotateMode(
        )

    def testRotateMode(self):
        """Test RotateMode"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
