# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.pdf_extract_text_parameters import PdfExtractTextParameters  # noqa: E501
from openapi_client.rest import ApiException

class TestPdfExtractTextParameters(unittest.TestCase):
    """PdfExtractTextParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PdfExtractTextParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.pdf_extract_text_parameters.PdfExtractTextParameters()  # noqa: E501
        if include_optional :
            return PdfExtractTextParameters(
                file_id = '0', 
                page_range = '0', 
                text_extraction_mode = 'WholePageReadable', 
                text_extraction_area_left = 1.337, 
                text_extraction_area_top = 1.337, 
                text_extraction_area_width = 1.337, 
                text_extraction_area_height = 1.337, 
                include_header = True
            )
        else :
            return PdfExtractTextParameters(
                file_id = '0',
                page_range = '0',
        )

    def testPdfExtractTextParameters(self):
        """Test PdfExtractTextParameters"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
