# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.document_api import DocumentApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.document_api.DocumentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_document_close(self):
        """Test case for document_close

        Closes a previously uploaded document.  # noqa: E501
        """
        pass

    def test_document_get_preview(self):
        """Test case for document_get_preview

        Gets the format, the page count and a thumbnail of a previously uploaded document.  # noqa: E501
        """
        pass

    def test_document_load(self):
        """Test case for document_load

        Loads the provided document file.  # noqa: E501
        """
        pass

    def test_document_load_from_uri(self):
        """Test case for document_load_from_uri

        Loads the provided document file from an URI.  # noqa: E501
        """
        pass

    def test_document_load_multipart(self):
        """Test case for document_load_multipart

        Loads the provided document file using Multipart Upload.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
