# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.link_annotation_parameters import LinkAnnotationParameters  # noqa: E501
from openapi_client.rest import ApiException

class TestLinkAnnotationParameters(unittest.TestCase):
    """LinkAnnotationParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LinkAnnotationParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.link_annotation_parameters.LinkAnnotationParameters()  # noqa: E501
        if include_optional :
            return LinkAnnotationParameters(
                annotation_layout = openapi_client.models.drawable_content_layout_parameters.DrawableContentLayoutParameters(
                    horizontal_position = 'Center', 
                    vertical_position = 'Center', 
                    size = 'Small', 
                    indent_from_edges = True, 
                    absolute_position_left = 1.337, 
                    absolute_position_top = 1.337, 
                    absolute_width = 1.337, 
                    absolute_height = 1.337, ), 
                link_type = 'Page', 
                link_page = 56, 
                link_uri = '0', 
                show_border = True, 
                color = 'red'
            )
        else :
            return LinkAnnotationParameters(
                annotation_layout = openapi_client.models.drawable_content_layout_parameters.DrawableContentLayoutParameters(
                    horizontal_position = 'Center', 
                    vertical_position = 'Center', 
                    size = 'Small', 
                    indent_from_edges = True, 
                    absolute_position_left = 1.337, 
                    absolute_position_top = 1.337, 
                    absolute_width = 1.337, 
                    absolute_height = 1.337, ),
        )

    def testLinkAnnotationParameters(self):
        """Test LinkAnnotationParameters"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
