# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.pdf_reduce_response import PdfReduceResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestPdfReduceResponse(unittest.TestCase):
    """PdfReduceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PdfReduceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.pdf_reduce_response.PdfReduceResponse()  # noqa: E501
        if include_optional :
            return PdfReduceResponse(
                error = openapi_client.models.error.Error(
                    result_code = 'OK', 
                    ext_result_status = '0', 
                    ext_result_message = '0', 
                    internal_error_id = '0', ), 
                remaining_tokens = 56, 
                error_info = openapi_client.models.reduce_error_info.ReduceErrorInfo(
                    error_code = 'OK', 
                    page_number = 56, 
                    ext_error_message = '0', ), 
                warnings_info = [
                    openapi_client.models.reduce_warning_info.ReduceWarningInfo(
                        warning_code = 'OK', 
                        page_number = 56, 
                        page_image_number = 56, 
                        ext_warning_message = '0', )
                    ], 
                content_removed = True, 
                version_changed = True, 
                new_file_size = 56
            )
        else :
            return PdfReduceResponse(
        )

    def testPdfReduceResponse(self):
        """Test PdfReduceResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
