# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.pdf_save_as_png_parameters import PdfSaveAsPNGParameters  # noqa: E501
from openapi_client.rest import ApiException

class TestPdfSaveAsPNGParameters(unittest.TestCase):
    """PdfSaveAsPNGParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PdfSaveAsPNGParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.pdf_save_as_png_parameters.PdfSaveAsPNGParameters()  # noqa: E501
        if include_optional :
            return PdfSaveAsPNGParameters(
                file_id = '0', 
                page_range = '*', 
                compression = 56, 
                interlaced = True, 
                resolution = 1.337, 
                render_form_fields = True, 
                keep_raster_pdf_resolution = True
            )
        else :
            return PdfSaveAsPNGParameters(
                file_id = '0',
        )

    def testPdfSaveAsPNGParameters(self):
        """Test PdfSaveAsPNGParameters"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
