# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.free_text_annotation_parameters import FreeTextAnnotationParameters  # noqa: E501
from openapi_client.rest import ApiException

class TestFreeTextAnnotationParameters(unittest.TestCase):
    """FreeTextAnnotationParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FreeTextAnnotationParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.free_text_annotation_parameters.FreeTextAnnotationParameters()  # noqa: E501
        if include_optional :
            return FreeTextAnnotationParameters(
                annotation_layout = openapi_client.models.drawable_content_layout_parameters.DrawableContentLayoutParameters(
                    horizontal_position = 'Center', 
                    vertical_position = 'Center', 
                    size = 'Small', 
                    indent_from_edges = True, 
                    absolute_position_left = 1.337, 
                    absolute_position_top = 1.337, 
                    absolute_width = 1.337, 
                    absolute_height = 1.337, ), 
                text_parameters = openapi_client.models.pdf_text_parameters.PdfTextParameters(
                    text = '0', 
                    text_color = 'black', 
                    font_name = '0', 
                    standard_font_name = 'Courier', 
                    font_style = 'Regular', 
                    font_size = 56, ), 
                title = '0', 
                subject = '0', 
                show_border = True, 
                color = 'red'
            )
        else :
            return FreeTextAnnotationParameters(
                annotation_layout = openapi_client.models.drawable_content_layout_parameters.DrawableContentLayoutParameters(
                    horizontal_position = 'Center', 
                    vertical_position = 'Center', 
                    size = 'Small', 
                    indent_from_edges = True, 
                    absolute_position_left = 1.337, 
                    absolute_position_top = 1.337, 
                    absolute_width = 1.337, 
                    absolute_height = 1.337, ),
        )

    def testFreeTextAnnotationParameters(self):
        """Test FreeTextAnnotationParameters"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
