# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class DocuViewareCertificate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'display_name': 'str',
        'data': 'str',
        'password': 'str',
        'timestamp_server_uri': 'str',
        'timestamp_server_user_name': 'str',
        'timestamp_server_user_password': 'str'
    }

    attribute_map = {
        'display_name': 'DisplayName',
        'data': 'Data',
        'password': 'Password',
        'timestamp_server_uri': 'TimestampServerURI',
        'timestamp_server_user_name': 'TimestampServerUserName',
        'timestamp_server_user_password': 'TimestampServerUserPassword'
    }

    def __init__(self, display_name=None, data=None, password=None, timestamp_server_uri=None, timestamp_server_user_name=None, timestamp_server_user_password=None, local_vars_configuration=None):  # noqa: E501
        """DocuViewareCertificate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._display_name = None
        self._data = None
        self._password = None
        self._timestamp_server_uri = None
        self._timestamp_server_user_name = None
        self._timestamp_server_user_password = None
        self.discriminator = None

        self.display_name = display_name
        self.data = data
        self.password = password
        self.timestamp_server_uri = timestamp_server_uri
        self.timestamp_server_user_name = timestamp_server_user_name
        self.timestamp_server_user_password = timestamp_server_user_password

    @property
    def display_name(self):
        """Gets the display_name of this DocuViewareCertificate.  # noqa: E501


        :return: The display_name of this DocuViewareCertificate.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this DocuViewareCertificate.


        :param display_name: The display_name of this DocuViewareCertificate.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def data(self):
        """Gets the data of this DocuViewareCertificate.  # noqa: E501


        :return: The data of this DocuViewareCertificate.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this DocuViewareCertificate.


        :param data: The data of this DocuViewareCertificate.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def password(self):
        """Gets the password of this DocuViewareCertificate.  # noqa: E501


        :return: The password of this DocuViewareCertificate.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this DocuViewareCertificate.


        :param password: The password of this DocuViewareCertificate.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def timestamp_server_uri(self):
        """Gets the timestamp_server_uri of this DocuViewareCertificate.  # noqa: E501


        :return: The timestamp_server_uri of this DocuViewareCertificate.  # noqa: E501
        :rtype: str
        """
        return self._timestamp_server_uri

    @timestamp_server_uri.setter
    def timestamp_server_uri(self, timestamp_server_uri):
        """Sets the timestamp_server_uri of this DocuViewareCertificate.


        :param timestamp_server_uri: The timestamp_server_uri of this DocuViewareCertificate.  # noqa: E501
        :type: str
        """

        self._timestamp_server_uri = timestamp_server_uri

    @property
    def timestamp_server_user_name(self):
        """Gets the timestamp_server_user_name of this DocuViewareCertificate.  # noqa: E501


        :return: The timestamp_server_user_name of this DocuViewareCertificate.  # noqa: E501
        :rtype: str
        """
        return self._timestamp_server_user_name

    @timestamp_server_user_name.setter
    def timestamp_server_user_name(self, timestamp_server_user_name):
        """Sets the timestamp_server_user_name of this DocuViewareCertificate.


        :param timestamp_server_user_name: The timestamp_server_user_name of this DocuViewareCertificate.  # noqa: E501
        :type: str
        """

        self._timestamp_server_user_name = timestamp_server_user_name

    @property
    def timestamp_server_user_password(self):
        """Gets the timestamp_server_user_password of this DocuViewareCertificate.  # noqa: E501


        :return: The timestamp_server_user_password of this DocuViewareCertificate.  # noqa: E501
        :rtype: str
        """
        return self._timestamp_server_user_password

    @timestamp_server_user_password.setter
    def timestamp_server_user_password(self, timestamp_server_user_password):
        """Sets the timestamp_server_user_password of this DocuViewareCertificate.


        :param timestamp_server_user_password: The timestamp_server_user_password of this DocuViewareCertificate.  # noqa: E501
        :type: str
        """

        self._timestamp_server_user_password = timestamp_server_user_password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocuViewareCertificate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocuViewareCertificate):
            return True

        return self.to_dict() != other.to_dict()
