# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class DocuViewareGetControlParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'session_id': 'str',
        'control_state': 'DocuViewareControlState'
    }

    attribute_map = {
        'session_id': 'SessionID',
        'control_state': 'ControlState'
    }

    def __init__(self, session_id=None, control_state=None, local_vars_configuration=None):  # noqa: E501
        """DocuViewareGetControlParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._session_id = None
        self._control_state = None
        self.discriminator = None

        self.session_id = session_id
        self.control_state = control_state

    @property
    def session_id(self):
        """Gets the session_id of this DocuViewareGetControlParameters.  # noqa: E501

        Specifies the unique identifier used to identify the user session.  # noqa: E501

        :return: The session_id of this DocuViewareGetControlParameters.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this DocuViewareGetControlParameters.

        Specifies the unique identifier used to identify the user session.  # noqa: E501

        :param session_id: The session_id of this DocuViewareGetControlParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and session_id is None:  # noqa: E501
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def control_state(self):
        """Gets the control_state of this DocuViewareGetControlParameters.  # noqa: E501


        :return: The control_state of this DocuViewareGetControlParameters.  # noqa: E501
        :rtype: DocuViewareControlState
        """
        return self._control_state

    @control_state.setter
    def control_state(self, control_state):
        """Sets the control_state of this DocuViewareGetControlParameters.


        :param control_state: The control_state of this DocuViewareGetControlParameters.  # noqa: E501
        :type: DocuViewareControlState
        """
        if self.local_vars_configuration.client_side_validation and control_state is None:  # noqa: E501
            raise ValueError("Invalid value for `control_state`, must not be `None`")  # noqa: E501

        self._control_state = control_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocuViewareGetControlParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocuViewareGetControlParameters):
            return True

        return self.to_dict() != other.to_dict()
