# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Font(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'font_style': 'FontStyle',
        'family_name': 'str'
    }

    attribute_map = {
        'font_style': 'FontStyle',
        'family_name': 'FamilyName'
    }

    def __init__(self, font_style=None, family_name=None, local_vars_configuration=None):  # noqa: E501
        """Font - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._font_style = None
        self._family_name = None
        self.discriminator = None

        if font_style is not None:
            self.font_style = font_style
        self.family_name = family_name

    @property
    def font_style(self):
        """Gets the font_style of this Font.  # noqa: E501


        :return: The font_style of this Font.  # noqa: E501
        :rtype: FontStyle
        """
        return self._font_style

    @font_style.setter
    def font_style(self, font_style):
        """Sets the font_style of this Font.


        :param font_style: The font_style of this Font.  # noqa: E501
        :type: FontStyle
        """

        self._font_style = font_style

    @property
    def family_name(self):
        """Gets the family_name of this Font.  # noqa: E501

        Specifies the family name of the font, i.e: \"Arial\".  # noqa: E501

        :return: The family_name of this Font.  # noqa: E501
        :rtype: str
        """
        return self._family_name

    @family_name.setter
    def family_name(self, family_name):
        """Sets the family_name of this Font.

        Specifies the family name of the font, i.e: \"Arial\".  # noqa: E501

        :param family_name: The family_name of this Font.  # noqa: E501
        :type: str
        """

        self._family_name = family_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Font):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Font):
            return True

        return self.to_dict() != other.to_dict()
