# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class GetDocumentPreviewParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_id': 'str',
        'thumbnail_width': 'int',
        'thumbnail_height': 'int',
        'thumbnail_background_color': 'str',
        'thumbnail_fit_to_page_size': 'bool'
    }

    attribute_map = {
        'file_id': 'FileId',
        'thumbnail_width': 'ThumbnailWidth',
        'thumbnail_height': 'ThumbnailHeight',
        'thumbnail_background_color': 'ThumbnailBackgroundColor',
        'thumbnail_fit_to_page_size': 'ThumbnailFitToPageSize'
    }

    def __init__(self, file_id=None, thumbnail_width=140, thumbnail_height=220, thumbnail_background_color='rgba(0,0,0,0)', thumbnail_fit_to_page_size=True, local_vars_configuration=None):  # noqa: E501
        """GetDocumentPreviewParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_id = None
        self._thumbnail_width = None
        self._thumbnail_height = None
        self._thumbnail_background_color = None
        self._thumbnail_fit_to_page_size = None
        self.discriminator = None

        self.file_id = file_id
        if thumbnail_width is not None:
            self.thumbnail_width = thumbnail_width
        if thumbnail_height is not None:
            self.thumbnail_height = thumbnail_height
        self.thumbnail_background_color = thumbnail_background_color
        if thumbnail_fit_to_page_size is not None:
            self.thumbnail_fit_to_page_size = thumbnail_fit_to_page_size

    @property
    def file_id(self):
        """Gets the file_id of this GetDocumentPreviewParameters.  # noqa: E501

        Specifies the identifier of the file to be previewed.  # noqa: E501

        :return: The file_id of this GetDocumentPreviewParameters.  # noqa: E501
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this GetDocumentPreviewParameters.

        Specifies the identifier of the file to be previewed.  # noqa: E501

        :param file_id: The file_id of this GetDocumentPreviewParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and file_id is None:  # noqa: E501
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def thumbnail_width(self):
        """Gets the thumbnail_width of this GetDocumentPreviewParameters.  # noqa: E501

        Specifies, in pixels, the width of the thumbnail to be retrieved.  # noqa: E501

        :return: The thumbnail_width of this GetDocumentPreviewParameters.  # noqa: E501
        :rtype: int
        """
        return self._thumbnail_width

    @thumbnail_width.setter
    def thumbnail_width(self, thumbnail_width):
        """Sets the thumbnail_width of this GetDocumentPreviewParameters.

        Specifies, in pixels, the width of the thumbnail to be retrieved.  # noqa: E501

        :param thumbnail_width: The thumbnail_width of this GetDocumentPreviewParameters.  # noqa: E501
        :type: int
        """

        self._thumbnail_width = thumbnail_width

    @property
    def thumbnail_height(self):
        """Gets the thumbnail_height of this GetDocumentPreviewParameters.  # noqa: E501

        Specifies, in pixels, the height of the thumbnail to be retrieved.  # noqa: E501

        :return: The thumbnail_height of this GetDocumentPreviewParameters.  # noqa: E501
        :rtype: int
        """
        return self._thumbnail_height

    @thumbnail_height.setter
    def thumbnail_height(self, thumbnail_height):
        """Sets the thumbnail_height of this GetDocumentPreviewParameters.

        Specifies, in pixels, the height of the thumbnail to be retrieved.  # noqa: E501

        :param thumbnail_height: The thumbnail_height of this GetDocumentPreviewParameters.  # noqa: E501
        :type: int
        """

        self._thumbnail_height = thumbnail_height

    @property
    def thumbnail_background_color(self):
        """Gets the thumbnail_background_color of this GetDocumentPreviewParameters.  # noqa: E501

        Specifies the background color of the thumbnail, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").  # noqa: E501

        :return: The thumbnail_background_color of this GetDocumentPreviewParameters.  # noqa: E501
        :rtype: str
        """
        return self._thumbnail_background_color

    @thumbnail_background_color.setter
    def thumbnail_background_color(self, thumbnail_background_color):
        """Sets the thumbnail_background_color of this GetDocumentPreviewParameters.

        Specifies the background color of the thumbnail, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").  # noqa: E501

        :param thumbnail_background_color: The thumbnail_background_color of this GetDocumentPreviewParameters.  # noqa: E501
        :type: str
        """

        self._thumbnail_background_color = thumbnail_background_color

    @property
    def thumbnail_fit_to_page_size(self):
        """Gets the thumbnail_fit_to_page_size of this GetDocumentPreviewParameters.  # noqa: E501

        Specifies if the size of the produced thumbnail is automatically adjusted to don't have any margin.  # noqa: E501

        :return: The thumbnail_fit_to_page_size of this GetDocumentPreviewParameters.  # noqa: E501
        :rtype: bool
        """
        return self._thumbnail_fit_to_page_size

    @thumbnail_fit_to_page_size.setter
    def thumbnail_fit_to_page_size(self, thumbnail_fit_to_page_size):
        """Sets the thumbnail_fit_to_page_size of this GetDocumentPreviewParameters.

        Specifies if the size of the produced thumbnail is automatically adjusted to don't have any margin.  # noqa: E501

        :param thumbnail_fit_to_page_size: The thumbnail_fit_to_page_size of this GetDocumentPreviewParameters.  # noqa: E501
        :type: bool
        """

        self._thumbnail_fit_to_page_size = thumbnail_fit_to_page_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetDocumentPreviewParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetDocumentPreviewParameters):
            return True

        return self.to_dict() != other.to_dict()
