# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PassportPDFStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OK = "OK"
    ACTIONTIMEDOUT = "ActionTimedOut"
    EMPTYPARAMETER = "EmptyParameter"
    INVALIDAPIKEY = "InvalidAPIKey"
    NOTENOUGHTOKENS = "NotEnoughTokens"
    GENERICERROR = "GenericError"
    INVALIDPARAMETER = "InvalidParameter"
    INVALIDCOLOR = "InvalidColor"
    OUTOFMEMORY = "OutOfMemory"
    NOTIMPLEMENTED = "NotImplemented"
    FILENOTFOUND = "FileNotFound"
    ACCESSDENIED = "AccessDenied"
    CANNOTIMPORTFILETOPDF = "CanNotImportFileToPDF"
    PDFCANNOTBEDECRYPTED = "PdfCanNotBeDecrypted"
    PDFOPERATIONNOTALLOWED = "PdfOperationNotAllowed"
    PDFCANNOTOPENFILE = "PdfCanNotOpenFile"
    PDFCANNOTSAVEFILE = "PdfCanNotSaveFile"
    CANNOTCREATEFILE = "CanNotCreateFile"
    NODOCUMENTPROVIDED = "NoDocumentProvided"
    CANNOTREMOVEPAGE = "CanNotRemovePage"
    CANNOTSWAPPAGES = "CanNotSwapPages"
    CANNOTMOVEPAGE = "CanNotMovePage"
    CANNOTROTATEPAGE = "CanNotRotatePage"
    CANNOTFLIPPAGE = "CanNotFlipPage"
    INVALIDPAGERANGE = "InvalidPageRange"
    CANNOTREDUCEPDF = "CanNotReducePDF"
    CANNOTAUTODESKEW = "CanNotAutoDeskew"
    CANNOTSPLIT = "CanNotSplit"
    CANNOTSAVEASJPEG = "CanNotSaveAsJPEG"
    CANNOTDIGISIGN = "CanNotDigiSign"
    CANNOTPROTECT = "CanNotProtect"
    CANNOTCONVERTTOPDFA = "CanNotConvertToPDFA"
    CANNOTANNOTATE = "CanNotAnnotate"
    CANNOTCLEARPAGE = "CanNotClearPage"
    CANNOTMERGE = "CanNotMerge"
    CANNOTGETPAGETHUMBNAIL = "CanNotGetPageThumbnail"
    CANNOTGETDOCUMENTPREVIEW = "CanNotGetDocumentPreview"
    CANNOTREMOVEPAGEFORMFIELDS = "CanNotRemovePageFormFields"
    CANNOTINSERTIMAGE = "CanNotInsertImage"
    CANNOTDRAWIMAGE = "CanNotDrawImage"
    CANNOTINSERTPAGENUMBER = "CanNotInsertPageNumber"
    CANNOTINSERTTEXT = "CanNotInsertText"
    CANNOTREADBARCODE = "CanNotReadBarcode"
    CANNOTFLATTEN = "CanNotFlatten"
    CANNOTEXPORTMORETHAN2GIGABYTEFILE = "CanNotExportMoreThan2GigabyteFile"
    CANNOTOPENSESSION = "CanNotOpenSession"
    UNKNOWNOREXPIREDSESSION = "UnknownOrExpiredSession"
    CANNOTSAVEFILE = "CanNotSaveFile"
    CANNOTREPAIRPDF = "CanNotRepairPDF"
    UNSUPPORTEDIMAGEFORMAT = "UnsupportedImageFormat"
    CANNOTOCR = "CanNotOCR"
    CANNOTOPENIMAGE = "CanNotOpenImage"
    CANNOTSAVEASPNG = "CanNotSaveAsPNG"
    CANNOTSAVEASTIFF = "CanNotSaveAsTIFF"
    CANNOTSAVEASTIFFMULTIPAGE = "CanNotSaveAsTIFFMultipage"
    CANNOTSETINFO = "CanNotSetInfo"
    CANNOTSETPAGEBOX = "CanNotSetPageBox"
    CANNOTEXTRACTPAGE = "CanNotExtractPage"
    CANNOTINSERTNEWPAGE = "CanNotInsertNewPage"
    CANNOTCLONEPAGE = "CanNotClonePage"
    CANNOTSETINITIALVIEW = "CanNotSetInitialView"
    CANNOTADJUST = "CanNotAdjust"
    CANNOTRESIZE = "CanNotResize"
    CANNOTFILTER = "CanNotFilter"
    CANNOTCLEANUPDOCUMENT = "CanNotCleanupDocument"
    UNKNOWNDOCUMENTFORMAT = "UnknownDocumentFormat"
    CANNOTCROP = "CanNotCrop"
    CANNOTROTATE = "CanNotRotate"
    CANNOTDETECTCOLOR = "CanNotDetectColor"
    CANNOTCONVERTCOLORDEPTH = "CanNotConvertColorDepth"
    PDFCANNOTADDFONT = "PdfCanNotAddFont"
    ACTIONEXECUTIONREJECTED = "ActionExecutionRejected"
    CANNOTEXTRACTTEXT = "CanNotExtractText"
    CANNOTDETECTBLANKPAGES = "CanNotDetectBlankPages"
    CANNOTMICR = "CanNotMICR"
    CANNOTDETECTPAGEORIENTATION = "CanNotDetectPageOrientation"
    CANNOTDELETEPAGE = "CanNotDeletePage"
    CANNOTSAVEASPDF = "CanNotSaveAsPDF"
    CANNOTEXTRACTIMAGE = "CanNotExtractImage"
    CANNOTCLONEIMAGEREGION = "CanNotCloneImageRegion"
    CANNOTREORDERPAGES = "CanNotReorderPages"
    CANNOTAUTOCROP = "CanNotAutoCrop"
    CANNOTSCALEPAGE = "CanNotScalePage"
    CANNOTMERGEPAGES = "CanNotMergePages"
    CANNOTGETMETADATA = "CanNotGetMetaData"
    CANNOTSETMETADATA = "CanNotSetMetadata"
    CANNOTREMOVETEXT = "CanNotRemoveText"
    CANNOTDOWNLOADDOCUMENT = "CanNotDownloadDocument"

    allowable_values = [OK, ACTIONTIMEDOUT, EMPTYPARAMETER, INVALIDAPIKEY, NOTENOUGHTOKENS, GENERICERROR, INVALIDPARAMETER, INVALIDCOLOR, OUTOFMEMORY, NOTIMPLEMENTED, FILENOTFOUND, ACCESSDENIED, CANNOTIMPORTFILETOPDF, PDFCANNOTBEDECRYPTED, PDFOPERATIONNOTALLOWED, PDFCANNOTOPENFILE, PDFCANNOTSAVEFILE, CANNOTCREATEFILE, NODOCUMENTPROVIDED, CANNOTREMOVEPAGE, CANNOTSWAPPAGES, CANNOTMOVEPAGE, CANNOTROTATEPAGE, CANNOTFLIPPAGE, INVALIDPAGERANGE, CANNOTREDUCEPDF, CANNOTAUTODESKEW, CANNOTSPLIT, CANNOTSAVEASJPEG, CANNOTDIGISIGN, CANNOTPROTECT, CANNOTCONVERTTOPDFA, CANNOTANNOTATE, CANNOTCLEARPAGE, CANNOTMERGE, CANNOTGETPAGETHUMBNAIL, CANNOTGETDOCUMENTPREVIEW, CANNOTREMOVEPAGEFORMFIELDS, CANNOTINSERTIMAGE, CANNOTDRAWIMAGE, CANNOTINSERTPAGENUMBER, CANNOTINSERTTEXT, CANNOTREADBARCODE, CANNOTFLATTEN, CANNOTEXPORTMORETHAN2GIGABYTEFILE, CANNOTOPENSESSION, UNKNOWNOREXPIREDSESSION, CANNOTSAVEFILE, CANNOTREPAIRPDF, UNSUPPORTEDIMAGEFORMAT, CANNOTOCR, CANNOTOPENIMAGE, CANNOTSAVEASPNG, CANNOTSAVEASTIFF, CANNOTSAVEASTIFFMULTIPAGE, CANNOTSETINFO, CANNOTSETPAGEBOX, CANNOTEXTRACTPAGE, CANNOTINSERTNEWPAGE, CANNOTCLONEPAGE, CANNOTSETINITIALVIEW, CANNOTADJUST, CANNOTRESIZE, CANNOTFILTER, CANNOTCLEANUPDOCUMENT, UNKNOWNDOCUMENTFORMAT, CANNOTCROP, CANNOTROTATE, CANNOTDETECTCOLOR, CANNOTCONVERTCOLORDEPTH, PDFCANNOTADDFONT, ACTIONEXECUTIONREJECTED, CANNOTEXTRACTTEXT, CANNOTDETECTBLANKPAGES, CANNOTMICR, CANNOTDETECTPAGEORIENTATION, CANNOTDELETEPAGE, CANNOTSAVEASPDF, CANNOTEXTRACTIMAGE, CANNOTCLONEIMAGEREGION, CANNOTREORDERPAGES, CANNOTAUTOCROP, CANNOTSCALEPAGE, CANNOTMERGEPAGES, CANNOTGETMETADATA, CANNOTSETMETADATA, CANNOTREMOVETEXT, CANNOTDOWNLOADDOCUMENT]  # noqa: E501

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None):  # noqa: E501
        """PassportPDFStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PassportPDFStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PassportPDFStatus):
            return True

        return self.to_dict() != other.to_dict()
