# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PdfExtractPageParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_id': 'str',
        'page_range': 'str',
        'extract_as_separate': 'bool',
        'immediate_download': 'bool'
    }

    attribute_map = {
        'file_id': 'FileId',
        'page_range': 'PageRange',
        'extract_as_separate': 'ExtractAsSeparate',
        'immediate_download': 'ImmediateDownload'
    }

    def __init__(self, file_id=None, page_range=None, extract_as_separate=False, immediate_download=False, local_vars_configuration=None):  # noqa: E501
        """PdfExtractPageParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_id = None
        self._page_range = None
        self._extract_as_separate = None
        self._immediate_download = None
        self.discriminator = None

        self.file_id = file_id
        self.page_range = page_range
        if extract_as_separate is not None:
            self.extract_as_separate = extract_as_separate
        if immediate_download is not None:
            self.immediate_download = immediate_download

    @property
    def file_id(self):
        """Gets the file_id of this PdfExtractPageParameters.  # noqa: E501

        The identifier of the previously uploaded file to be processed.  # noqa: E501

        :return: The file_id of this PdfExtractPageParameters.  # noqa: E501
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this PdfExtractPageParameters.

        The identifier of the previously uploaded file to be processed.  # noqa: E501

        :param file_id: The file_id of this PdfExtractPageParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and file_id is None:  # noqa: E501
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def page_range(self):
        """Gets the page_range of this PdfExtractPageParameters.  # noqa: E501

        Specifies the number of the page, or the range of pages to be extracted.  # noqa: E501

        :return: The page_range of this PdfExtractPageParameters.  # noqa: E501
        :rtype: str
        """
        return self._page_range

    @page_range.setter
    def page_range(self, page_range):
        """Sets the page_range of this PdfExtractPageParameters.

        Specifies the number of the page, or the range of pages to be extracted.  # noqa: E501

        :param page_range: The page_range of this PdfExtractPageParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and page_range is None:  # noqa: E501
            raise ValueError("Invalid value for `page_range`, must not be `None`")  # noqa: E501

        self._page_range = page_range

    @property
    def extract_as_separate(self):
        """Gets the extract_as_separate of this PdfExtractPageParameters.  # noqa: E501

        Specifies whether each extracted page shall form a separate document.  # noqa: E501

        :return: The extract_as_separate of this PdfExtractPageParameters.  # noqa: E501
        :rtype: bool
        """
        return self._extract_as_separate

    @extract_as_separate.setter
    def extract_as_separate(self, extract_as_separate):
        """Sets the extract_as_separate of this PdfExtractPageParameters.

        Specifies whether each extracted page shall form a separate document.  # noqa: E501

        :param extract_as_separate: The extract_as_separate of this PdfExtractPageParameters.  # noqa: E501
        :type: bool
        """

        self._extract_as_separate = extract_as_separate

    @property
    def immediate_download(self):
        """Gets the immediate_download of this PdfExtractPageParameters.  # noqa: E501

        Specifies whether the file(s) created as a result of the action shall be available for immediate download.  # noqa: E501

        :return: The immediate_download of this PdfExtractPageParameters.  # noqa: E501
        :rtype: bool
        """
        return self._immediate_download

    @immediate_download.setter
    def immediate_download(self, immediate_download):
        """Sets the immediate_download of this PdfExtractPageParameters.

        Specifies whether the file(s) created as a result of the action shall be available for immediate download.  # noqa: E501

        :param immediate_download: The immediate_download of this PdfExtractPageParameters.  # noqa: E501
        :type: bool
        """

        self._immediate_download = immediate_download

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PdfExtractPageParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PdfExtractPageParameters):
            return True

        return self.to_dict() != other.to_dict()
