# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PdfOCRParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_id': 'str',
        'page_range': 'str',
        'language': 'str',
        'skip_page_with_text': 'bool'
    }

    attribute_map = {
        'file_id': 'FileId',
        'page_range': 'PageRange',
        'language': 'Language',
        'skip_page_with_text': 'SkipPageWithText'
    }

    def __init__(self, file_id=None, page_range=None, language='eng', skip_page_with_text=True, local_vars_configuration=None):  # noqa: E501
        """PdfOCRParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_id = None
        self._page_range = None
        self._language = None
        self._skip_page_with_text = None
        self.discriminator = None

        self.file_id = file_id
        self.page_range = page_range
        self.language = language
        if skip_page_with_text is not None:
            self.skip_page_with_text = skip_page_with_text

    @property
    def file_id(self):
        """Gets the file_id of this PdfOCRParameters.  # noqa: E501

        The identifier of the previously uploaded file to be processed.  # noqa: E501

        :return: The file_id of this PdfOCRParameters.  # noqa: E501
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this PdfOCRParameters.

        The identifier of the previously uploaded file to be processed.  # noqa: E501

        :param file_id: The file_id of this PdfOCRParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and file_id is None:  # noqa: E501
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def page_range(self):
        """Gets the page_range of this PdfOCRParameters.  # noqa: E501

        Specifies the page or the page range to be processed.  # noqa: E501

        :return: The page_range of this PdfOCRParameters.  # noqa: E501
        :rtype: str
        """
        return self._page_range

    @page_range.setter
    def page_range(self, page_range):
        """Sets the page_range of this PdfOCRParameters.

        Specifies the page or the page range to be processed.  # noqa: E501

        :param page_range: The page_range of this PdfOCRParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and page_range is None:  # noqa: E501
            raise ValueError("Invalid value for `page_range`, must not be `None`")  # noqa: E501

        self._page_range = page_range

    @property
    def language(self):
        """Gets the language of this PdfOCRParameters.  # noqa: E501

        Specifies the language to be used for the OCR.  # noqa: E501

        :return: The language of this PdfOCRParameters.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this PdfOCRParameters.

        Specifies the language to be used for the OCR.  # noqa: E501

        :param language: The language of this PdfOCRParameters.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def skip_page_with_text(self):
        """Gets the skip_page_with_text of this PdfOCRParameters.  # noqa: E501

        Specifies if pages containing text must be ignored (in such case no token is charged).  # noqa: E501

        :return: The skip_page_with_text of this PdfOCRParameters.  # noqa: E501
        :rtype: bool
        """
        return self._skip_page_with_text

    @skip_page_with_text.setter
    def skip_page_with_text(self, skip_page_with_text):
        """Sets the skip_page_with_text of this PdfOCRParameters.

        Specifies if pages containing text must be ignored (in such case no token is charged).  # noqa: E501

        :param skip_page_with_text: The skip_page_with_text of this PdfOCRParameters.  # noqa: E501
        :type: bool
        """

        self._skip_page_with_text = skip_page_with_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PdfOCRParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PdfOCRParameters):
            return True

        return self.to_dict() != other.to_dict()
