# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PdfConvertToPDFAParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_id': 'str',
        'conformance': 'PdfAConformance',
        'allow_vectorization': 'bool',
        'allow_rasterization': 'bool'
    }

    attribute_map = {
        'file_id': 'FileId',
        'conformance': 'Conformance',
        'allow_vectorization': 'AllowVectorization',
        'allow_rasterization': 'AllowRasterization'
    }

    def __init__(self, file_id=None, conformance=None, allow_vectorization=True, allow_rasterization=True, local_vars_configuration=None):  # noqa: E501
        """PdfConvertToPDFAParameters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_id = None
        self._conformance = None
        self._allow_vectorization = None
        self._allow_rasterization = None
        self.discriminator = None

        self.file_id = file_id
        if conformance is not None:
            self.conformance = conformance
        if allow_vectorization is not None:
            self.allow_vectorization = allow_vectorization
        if allow_rasterization is not None:
            self.allow_rasterization = allow_rasterization

    @property
    def file_id(self):
        """Gets the file_id of this PdfConvertToPDFAParameters.  # noqa: E501

        The identifier of the previously uploaded file to be processed.  # noqa: E501

        :return: The file_id of this PdfConvertToPDFAParameters.  # noqa: E501
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this PdfConvertToPDFAParameters.

        The identifier of the previously uploaded file to be processed.  # noqa: E501

        :param file_id: The file_id of this PdfConvertToPDFAParameters.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and file_id is None:  # noqa: E501
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def conformance(self):
        """Gets the conformance of this PdfConvertToPDFAParameters.  # noqa: E501


        :return: The conformance of this PdfConvertToPDFAParameters.  # noqa: E501
        :rtype: PdfAConformance
        """
        return self._conformance

    @conformance.setter
    def conformance(self, conformance):
        """Sets the conformance of this PdfConvertToPDFAParameters.


        :param conformance: The conformance of this PdfConvertToPDFAParameters.  # noqa: E501
        :type: PdfAConformance
        """

        self._conformance = conformance

    @property
    def allow_vectorization(self):
        """Gets the allow_vectorization of this PdfConvertToPDFAParameters.  # noqa: E501

        If set to true, conversion engine will use the page vectorization in case direct conversion is not possible.  # noqa: E501

        :return: The allow_vectorization of this PdfConvertToPDFAParameters.  # noqa: E501
        :rtype: bool
        """
        return self._allow_vectorization

    @allow_vectorization.setter
    def allow_vectorization(self, allow_vectorization):
        """Sets the allow_vectorization of this PdfConvertToPDFAParameters.

        If set to true, conversion engine will use the page vectorization in case direct conversion is not possible.  # noqa: E501

        :param allow_vectorization: The allow_vectorization of this PdfConvertToPDFAParameters.  # noqa: E501
        :type: bool
        """

        self._allow_vectorization = allow_vectorization

    @property
    def allow_rasterization(self):
        """Gets the allow_rasterization of this PdfConvertToPDFAParameters.  # noqa: E501

        If set to true, conversion engine will use the page rasterization in case direct conversion and verorization are not possible or allowed.  # noqa: E501

        :return: The allow_rasterization of this PdfConvertToPDFAParameters.  # noqa: E501
        :rtype: bool
        """
        return self._allow_rasterization

    @allow_rasterization.setter
    def allow_rasterization(self, allow_rasterization):
        """Sets the allow_rasterization of this PdfConvertToPDFAParameters.

        If set to true, conversion engine will use the page rasterization in case direct conversion and verorization are not possible or allowed.  # noqa: E501

        :param allow_rasterization: The allow_rasterization of this PdfConvertToPDFAParameters.  # noqa: E501
        :type: bool
        """

        self._allow_rasterization = allow_rasterization

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PdfConvertToPDFAParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PdfConvertToPDFAParameters):
            return True

        return self.to_dict() != other.to_dict()
