# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PdfSaveAsTIFFMultipageResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error': 'Error',
        'remaining_tokens': 'int',
        'image_data': 'str',
        'file_name': 'str'
    }

    attribute_map = {
        'error': 'Error',
        'remaining_tokens': 'RemainingTokens',
        'image_data': 'ImageData',
        'file_name': 'FileName'
    }

    def __init__(self, error=None, remaining_tokens=None, image_data=None, file_name=None, local_vars_configuration=None):  # noqa: E501
        """PdfSaveAsTIFFMultipageResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._error = None
        self._remaining_tokens = None
        self._image_data = None
        self._file_name = None
        self.discriminator = None

        if error is not None:
            self.error = error
        if remaining_tokens is not None:
            self.remaining_tokens = remaining_tokens
        self.image_data = image_data
        self.file_name = file_name

    @property
    def error(self):
        """Gets the error of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501


        :return: The error of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :rtype: Error
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this PdfSaveAsTIFFMultipageResponse.


        :param error: The error of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :type: Error
        """

        self._error = error

    @property
    def remaining_tokens(self):
        """Gets the remaining_tokens of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501

        Specifies the number of remaining tokens.  # noqa: E501

        :return: The remaining_tokens of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :rtype: int
        """
        return self._remaining_tokens

    @remaining_tokens.setter
    def remaining_tokens(self, remaining_tokens):
        """Sets the remaining_tokens of this PdfSaveAsTIFFMultipageResponse.

        Specifies the number of remaining tokens.  # noqa: E501

        :param remaining_tokens: The remaining_tokens of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :type: int
        """

        self._remaining_tokens = remaining_tokens

    @property
    def image_data(self):
        """Gets the image_data of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501

        Specifies the data of the produced multipage TIFF.  # noqa: E501

        :return: The image_data of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :rtype: str
        """
        return self._image_data

    @image_data.setter
    def image_data(self, image_data):
        """Sets the image_data of this PdfSaveAsTIFFMultipageResponse.

        Specifies the data of the produced multipage TIFF.  # noqa: E501

        :param image_data: The image_data of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :type: str
        """

        self._image_data = image_data

    @property
    def file_name(self):
        """Gets the file_name of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501

        Specifies the name of the saved document.  # noqa: E501

        :return: The file_name of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this PdfSaveAsTIFFMultipageResponse.

        Specifies the name of the saved document.  # noqa: E501

        :param file_name: The file_name of this PdfSaveAsTIFFMultipageResponse.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PdfSaveAsTIFFMultipageResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PdfSaveAsTIFFMultipageResponse):
            return True

        return self.to_dict() != other.to_dict()
