# coding: utf-8

"""
    PassportPDF API

    Another brick in the cloud  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ReduceWarningInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'warning_code': 'ReduceWarningCode',
        'page_number': 'int',
        'page_image_number': 'int',
        'ext_warning_message': 'str'
    }

    attribute_map = {
        'warning_code': 'WarningCode',
        'page_number': 'PageNumber',
        'page_image_number': 'PageImageNumber',
        'ext_warning_message': 'ExtWarningMessage'
    }

    def __init__(self, warning_code=None, page_number=None, page_image_number=None, ext_warning_message=None, local_vars_configuration=None):  # noqa: E501
        """ReduceWarningInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._warning_code = None
        self._page_number = None
        self._page_image_number = None
        self._ext_warning_message = None
        self.discriminator = None

        if warning_code is not None:
            self.warning_code = warning_code
        if page_number is not None:
            self.page_number = page_number
        if page_image_number is not None:
            self.page_image_number = page_image_number
        self.ext_warning_message = ext_warning_message

    @property
    def warning_code(self):
        """Gets the warning_code of this ReduceWarningInfo.  # noqa: E501


        :return: The warning_code of this ReduceWarningInfo.  # noqa: E501
        :rtype: ReduceWarningCode
        """
        return self._warning_code

    @warning_code.setter
    def warning_code(self, warning_code):
        """Sets the warning_code of this ReduceWarningInfo.


        :param warning_code: The warning_code of this ReduceWarningInfo.  # noqa: E501
        :type: ReduceWarningCode
        """

        self._warning_code = warning_code

    @property
    def page_number(self):
        """Gets the page_number of this ReduceWarningInfo.  # noqa: E501

        The number of the page processed when the warning occured.  # noqa: E501

        :return: The page_number of this ReduceWarningInfo.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this ReduceWarningInfo.

        The number of the page processed when the warning occured.  # noqa: E501

        :param page_number: The page_number of this ReduceWarningInfo.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def page_image_number(self):
        """Gets the page_image_number of this ReduceWarningInfo.  # noqa: E501

        The number of the image of the page processed when the warning occured.  # noqa: E501

        :return: The page_image_number of this ReduceWarningInfo.  # noqa: E501
        :rtype: int
        """
        return self._page_image_number

    @page_image_number.setter
    def page_image_number(self, page_image_number):
        """Sets the page_image_number of this ReduceWarningInfo.

        The number of the image of the page processed when the warning occured.  # noqa: E501

        :param page_image_number: The page_image_number of this ReduceWarningInfo.  # noqa: E501
        :type: int
        """

        self._page_image_number = page_image_number

    @property
    def ext_warning_message(self):
        """Gets the ext_warning_message of this ReduceWarningInfo.  # noqa: E501

        The warning message associated with the warning, if any.  # noqa: E501

        :return: The ext_warning_message of this ReduceWarningInfo.  # noqa: E501
        :rtype: str
        """
        return self._ext_warning_message

    @ext_warning_message.setter
    def ext_warning_message(self, ext_warning_message):
        """Sets the ext_warning_message of this ReduceWarningInfo.

        The warning message associated with the warning, if any.  # noqa: E501

        :param ext_warning_message: The ext_warning_message of this ReduceWarningInfo.  # noqa: E501
        :type: str
        """

        self._ext_warning_message = ext_warning_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReduceWarningInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReduceWarningInfo):
            return True

        return self.to_dict() != other.to_dict()
